analytics_cluster = "america.analytics.controld.com"

batch_size = 200
concurrency_limit = 5
rule_limit = 10000

[[rules]]
rule = "Spam TLDs/IDNs"
profile_rule = "none" # options: block, allow, none (none uses the JSON's internal actions)
excluded_profiles = ["iot", "guest", "user_k"]
rule_url = [
"https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/controld/spam-tlds-combined-folder.json",
]

[[rules]]
rule = "Badware Hoster"
profile_rule = "none"
excluded_profiles = ["iot", "guest", "user_k"]
rule_url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/controld/badware-hoster-folder.json"
]
